In [2]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [4]:
df.head(2)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
#snake case the column names
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ' , '_')
df = df.rename(columns = {"purchase_amount_(usd)":"purchase_amount"} )

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
len(df.columns)

18

In [14]:
labels = ["Young Adult" ,"Adult" , "Middle-aged" , "Senior"]
df['age_group'] = pd.qcut(df['age'] , q=4 , labels = labels )

In [15]:
df[['age' , 'age_group']].head(300)

     age    age_group
0     55  Middle-aged
1     19  Young Adult
2     50  Middle-aged
3     21  Young Adult
4     45  Middle-aged
..   ...          ...
295   53  Middle-aged
296   25  Young Adult
297   48  Middle-aged
298   69       Senior
299   25  Young Adult

[300 rows x 2 columns]

In [18]:
frequency_mapping = {
    "Annually" : 365,
    "Bi-Weekly" : 14,
    "Weekly" : 7,
    "Monthly" : 30,
    "Fortnightly" : 14,
    "Every 3 Months" : 90,
    "Quarterly" : 90
}

df['purchase_frequency_days'] =  df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['frequency_of_purchases' , 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [20]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [21]:
df = df.drop('promo_code_used', axis = 1)

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [24]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.2-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\usama.arshad\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 291.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 291.3 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 291.3 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 327.9 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 327.9 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 327.9 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 327.9 kB/s eta 0:00:07
   ----------- ---------------------------- 0.8/2.8 MB 327.9 kB/s eta 0:00:07
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 316.9 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ------------------- -------------------- 1.3/2.8 MB 255.2 kB/s eta 0:00:06
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   ---------------------- ----------------- 1.6/2.8 MB 146.5 kB/s eta 0:00:09
   -------------------------- ------------- 1.8/2.8 MB 141.9 kB/s eta 0:00:07
   -------------------------- ------------- 1.8/2.8 MB 141.9 kB/s eta 0:00:07
   -------------------------- ------------- 1.8/2.8 MB 141.9 kB/s eta 0:00:07
   -------------------------- ------------- 1.8/2.8 MB 141.9 kB/s eta 0:00:07
   -------------------------- ------------- 1.8/2.8 MB 141.9 kB/s eta 0:00:07
   ------------------------------ --------- 2.1/2.8 MB 150.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.1/2.8 MB 150.8 kB/s eta 0:00:05
   ------------------------------ --------- 2.1/2.8 MB 150.8 kB/s eta 0:00:05
   ---------------------------------- ----- 2.4/2.8 MB 163.8 kB/s eta 0:00:03
   ---------------------------------- ----- 2.4/2.8 MB 163.8 kB/s eta 0:00:03
   ---------------------------------- ----- 2.4/2.8 MB 163.8 kB/s eta 0:00:03
   -------------------------------------- - 2.6/2.8 MB 175.5 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 181.7 kB/s  0:00:15
Downloading sqlalchemy-2.0.51-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 551.6 kB/s eta 0:00:03
   --------- ------------------------------ 0.5/2.1 MB 551.6 kB/s eta 0:00:03
   --------- ------------------------------ 0.5/2.1 MB 551.6 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 479.5 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 479.5 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 479.5 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.1 MB 479.5 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 411.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 411.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 411.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 411.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 411.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 377.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 377.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 377.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 377.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 377.7 kB/s eta 0:00:03
   ----------------------------- ---------- 1.6/2.1 MB 337.9 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 337.9 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 337.9 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 337.9 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 337.9 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 321.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 321.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 321.8 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 321.8 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 316.9 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 317.7 kB/s  0:00:06
Downloading greenlet-3.5.2-cp313-cp313-win_amd64.whl (239 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.2 psycopg2-binary-2.9.12 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [30]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Usamasial0012@")
host = "localhost"
port = "5432"
database = "Customer_Behaviour"

engine = create_engine(
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)
table_name = "customer"
df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print("Data is successfully loaded")

Data is successfully loaded